name: gh-pages-release

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.0
     
    - name: install
      run: cd go-touch-mapper-gh-pages && yarn install
      
    - name: build
      run: cd go-touch-mapper-gh-pages && yarn build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./go-touch-mapper-gh-pages/build
